database:
  driver: "postgres"
  host: "localhost"
  name: "simple_dating_app"
  password: "postgres"
  port: 5432
  user: "postgres"
  default_timeout: 5

token:
  default_expiration: 1
  jwt_key: "J8rCtzsJbsXKtDDkIagxdhauklUiOnh5"

premium:
  mapPackagetoID:
    "verified": 1
    "infinite": 2
